# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UXThinkBig_TextField' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UXThinkBig_TextField
  pod 'SnapKit'
  pod 'Then'
end
